### ISSUE TITLE
Сумма на счете при пополнении не добавляется к начальному балансу

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#10]
# Описание
Тестируем расчёт Balance при пополнении, когда сумма initialBalance и amount равна MaxBalance
initialBalance = 10, amount = 90, их сумма равна MaxBalance = 100
Cогласно формуле Balance = Balance + amount = 100,
но получаем 10, т.е. фактически формула не срабатывает.

# Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67

# Шаги воспроизведения
**1** Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
**2** Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance = 10,
* сумма amount = 90,
* максимальный баланс maxBalance = 100,
* ставка rate = 5.

**3** Запустить метод расчёта Balance при пополнении
**4** Посмотреть на результат в консоли
*Ожидаемый результат*: 100
*Фактический результат*: 10

# Локация теста

https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L103

# Скриншот
![Скриншот 06-10-2024 024339](https://github.com/user-attachments/assets/3f524aec-bdb3-42b1-9364-8ea0cf791426)

# Окружение
*Операционная система*: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Добавила суммирование и возможность сумме баланса и пополнения быть равной максимальному балансу
if (balance + amount <= maxBalance) {
            balance += amount;
