### ISSUE TITLE
Не срабатывает exseption при создании счета если минимальный баланс больше масксимального

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#11]
# Описание
Тестируем негативный сценарий с возвращением IllegalArgumentException когда MinBalance больше MaxBalance

# Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
*1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
*2* Создать объект класса SavingAccount со значениями:
* начальный баланс initialBalance = 100,
* максимальный баланс maxBalance = 50,
* минимальный баланс minBalance = 100,
* ставка rate = 5.
*3* Запустить негативный сценарий с возвращением IllegalArgumentException 
*4* Посмотреть на результат в консоли

**Ожидаемый результат**: сработало исключение
**Фактический результат**: исключение не сработало

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L11

# Скриншот
![Скриншот 06-10-2024 160750](https://github.com/user-attachments/assets/cd76e6d7-3c16-4e34-ad20-dac1d82cf00d)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Добавила проверку
 if (minBalance > maxBalance) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть больше чем максимальный баланс"
            );
        }
