### ISSUE TITLE
Не срабатывает exseption при создании счета если начальный баланс отрицательный

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#12]
# Описание
Тестируем негативный сценарий с возвращением IllegalArgumentException когда InitialBalance меньше нуля

# Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения

*1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
*2* Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance = -100,
* минимальный баланс minBalance = 100,

* максимальный баланс maxBalance = 250,
* ставка rate = 5.
*3* Запустить негативный сценарий создания счета с возвращением exception
*4* Посмотреть на результат в консоли
*Ожидаемый результат*: срабатывает исключение
*Фактический результат*: исключение не срабатывает

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L21

# Скриншот
![Скриншот 06-10-2024 182808](https://github.com/user-attachments/assets/5a4c3d27-dbd9-4acc-8a79-dd04ff3c11b4)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Добавила проверку:
 if (initialBalance < 0) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть отрицательным, а у вас: " + initialBalance
            );
        }
