### ISSUE TITLE
Исключение не срабатывает в счете если MinBalance и MaxBalance меньше 0

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#14]
# Описание
 Тестируем негативный сценарий с возвращением IllegalArgumentException
    //когда MinBalance и MaxBalance меньше 0

 # Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23
 
 # Шаги воспроизведения
 *1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
*2* Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance = 100,
* минимальный баланс minBalance = -100,
* максимальный баланс maxBalance = -150,
* ставка rate = 5.
*3* Запустить метод негативного сценария с возвращением IllegalArgumentException
*4* Посмотреть на результат в консоли
*Ожидаемый результат*: сработало Exception
*Фактический результат*: Exception не сработало

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L32

# Скриншот
![Скриншот 08-10-2024 165500](https://github.com/user-attachments/assets/c2eb1bcf-c256-4666-a78a-d0c3c0c93505)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Добавила код 
 if (minBalance < 0) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть отрицательным, а у вас: " + minBalance
            );
        }
        if (maxBalance < 0) {
            throw new IllegalArgumentException(
                    "Максимальный баланс не может быть отрицательным, а у вас: " + maxBalance
            );
        }
