### ISSUE TITLE
Исключение не срабатывает в счете когда InitialBalance меньше MinBalance

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#15]
# Описание
Тестируем негативный сценарий с возвращением IllegalArgumentException, когда InitialBalance меньше MinBalance

 # Локация дефекта
 https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23
 
 # Шаги воспроизведения
 *1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
*2* Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance =10,
* минимальный баланс minBalance = 50,
* максимальный баланс maxBalance =150,
* ставка rate = 5.
*3* Запустить метод негативного сценария с возвращением IllegalArgumentException
*4* Посмотреть на результат в консоли
*Ожидаемый результат*: сработало Exception
*Фактический результат*: Exception не сработало

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L43

# Скриншот
![Скриншот 08-10-2024 170437](https://github.com/user-attachments/assets/bc200aa3-6ec6-4e2d-9786-5e3ae6498498)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
if (initialBalance < minBalance) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть меньше чем минимальный баланс, а у вас: " + initialBalance
            );
        }
