### ISSUE TITLE
Исключение работает при негативном сценарии когда Rate меньше нуля

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#17]
# Описание
Тестируем негативный сценарий с возвращением IllegalArgumentException когда Rate меньше нуля

 # Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23
 
 # Шаги воспроизведения
 *1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
*2* Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance =150,
* минимальный баланс minBalance = 50,
* максимальный баланс maxBalance = 250,
* ставка rate =  -5.
*3* Запустить метод негативного сценария с возвращением IllegalArgumentException
*4* Посмотреть на результат в консоли
*Ожидаемый результат*: сработало Exception
*Фактический результат*: сработало Exception

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/e4c7b2a8b22ec911cce07a520fb7d2e56cbd92b0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L65

# Скриншот
![Скриншот 08-10-2024 213633](https://github.com/user-attachments/assets/9b27e67d-7e07-451e-87f2-f902306aab20)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
когда работает, баг-репорт не нужен
