### ISSUE TITLE
Начальный баланс ниже минимального на счете при пополнении становится минусовым

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#8]
# Описание
Тестируем расчёт Balance при оплате, когда Balance меньше MinBalance
    initialBalance = -5, т.е. меньше MinBalance = 0
    согласно условию Balance не должен меняться,
    но получаем на консоли -7, т.е. фактически срабатывает формула вне зависимости от условия

# Локация дефекта
 {https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L46
 
 # Шаги воспроизведения
 *1* Открыть [код программы](https://vk.cc/cBUCO6) в IDEA
 *2* Создать объект класса  SavingAccount со значениями:
 - начальный баланс initialBalance = -5,
 - минимальный баланс  minBalance = 0,
 - максимальный баланс maxBalance = 100,
 - ставка rate = 5.
*3* Запустить метод расчёта Balance при оплате
*4* Посмотреть на результат в консоли
 
*Ожидаемый результат:* -5
*Фактический результат:* -7

# Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L65

# Скриншот
![Скриншот 04-10-2024 153515](https://github.com/user-attachments/assets/2f4c9a9f-1f59-4b86-9cc7-0646bac13767)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:**  IntelliJ IDEA 2024.2.3 (Community Edition)
*  **Java:** OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Тут должно проверяться исключение вида IllegalArgumentException.
Начальный баланс не может быть меньше чем минимальный баланс

**Comment by Jane-Popova** [comment]
Добавила код
if (initialBalance < minBalance) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть меньше чем минимальный баланс, а у вас: " + initialBalance
            );
        }
