### ISSUE TITLE
Сумма на счете при пополнении не суммируется с начальным балансом

### ISSUE THREAD

**Issue by YuluyaS** [Jane-Popova/javaqaTeamProject#9]
# Описание
Тестируем расчёт Balance при пополнении, когда сумма initialBalance и amount меньше MaxBalance.
initialBalance = 10, amount = 70, их сумма меньше MaxBalance = 100.
Согласно формуле Balance = Balance + amount = 80,  но получаем 70, т.е. фактически Balance = amount

# Локация дефекта
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67

# Шаги воспроизведения
*1* Открыть <a href="https://vk.cc/cBUCO6" target="_blank" style="text-decoration:none;">код программы</a> в IDEA
*2* Создать объект класса SavingAccount со значениями:

* начальный баланс initialBalance = 10,
* сумма  amount = 70,
* максимальный баланс maxBalance = 100,
* ставка rate = 5.
*3* Запустить метод расчёта Balance при пополнении
*4* Посмотреть на результат в консоли
*Ожидаемый результат*: 80
*Фактический результат*: 70

 # Локация теста
https://github.com/Jane-Popova/javaqaTeamProject/blob/7761d7ca586f82fd0f8ebd9fb6c84ea0e61f3490/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L84

# Скриншот
![Скриншот 06-10-2024 021959](https://github.com/user-attachments/assets/ab73c69a-193e-4743-9a8b-66fd72af2f2a)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2024.2.3 (Community Edition)
Java: OpenJDK 11.0.24

**Comment by Jane-Popova** [comment]
Добавила суммирование balance += amount;
